
[[plugins]]
repository = 'kshenoy/vim-signature'

[[plugins]]
repository = 'tpope/vim-dispatch'

# Unite {{{
[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'Shougo/neomru.vim'
filetypes  = 'all'

[[plugins]]
repository = 'Shougo/unite.vim'
depends    = 'Shougo/neomru.vim'
    [plugins.commands]
    name     = 'Unite'
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/unite-help'
# }}}

# Snippets / Completion {{{
[[plugins]]
repository = 'Shougo/neocomplete'
depends    = 'Shougo/context_filetype.vim'
insert     = 1 # Autoload when enter in insert mode
# }}}
# UI {{{
[[plugins]]
repository = 'itchyny/lightline.vim'

# ## Colorschemes {{{
[[plugins]]
repository = 'w0ng/vim-hybrid'

[[plugins]]
repository = 'chriskempson/base16-vim'

[[plugins]]
repository = 'altercation/vim-colors-solarized'
# ## }}}
# }}}

[[plugins]]
repository = 'xolox/vim-notes'
depends    = 'xolox/vim-misc'

# Development {{{
# ## SQL{{{
[[plugins]]
repository = 'sqlserver.vim'
filetypes  = 'sql'
# ## }}}
# ## Powershell {{{
[[plugins]]
repository = 'PProvost/vim-ps1'
# ## }}}
# ## Git {{{
[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'gregsexton/gitv'
depends    = 'tpope/vim-fugitive'
commands   = 'Gtiv'

[[plugins]]
repository = 'rhysd/committia.vim'
# ## }}}
## Rust {{{
[[plugins]]
repository = 'rust-lang/rust.vim'
filetype   = 'rs'

[[plugins]]
repository = 'phildawes/racer'

# ## }}}
# ## Syntastic {{{
[[plugins]]
repository = 'srooloose/syntastic'

[[plugins]]
repository = 'syngan/vim-vimlint'
depends    = 'ynkdir/vim-vimlparser'
# }}}

# Filetypes {{{
[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'
# }}}

# TODO: TO TEST
[[plugins]]
repository = "OrangeT/vim-csharp"

# vim: set foldmethod=marker:
