
[[plugins]]
repository = 'kshenoy/vim-signature'

[[plugins]]
repository = 'tpope/vim-dispatch'

# Unite {{{
[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'Shougo/neomru.vim'
filetypes  = 'all'

[[plugins]]
repository = 'Shougo/unite.vim'
depends    = 'Shougo/neomru.vim'
    [plugins.commands]
    name     = 'Unite'
    complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/unite-help'
# }}}

# Snippets / Completion {{{
[[plugins]]
repository = 'Shougo/neocomplete'
depends    = 'Shougo/context_filetype.vim'
insert     = 1 # Autoload when enter in insert mode
# }}}

[[plugins]]
repository = 'xolox/vim-notes'
depends    = 'xolox/vim-misc'

# Development {{{
## Rust {{{
[[plugins]]
repository = 'phildawes/racer'
# ## }}}
# ## Syntastic {{{
[[plugins]]
repository = 'srooloose/syntastic'

[[plugins]]
repository = 'syngan/vim-vimlint'
depends    = 'ynkdir/vim-vimlparser'
# }}}

# Filetypes {{{
[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'
# }}}

# TODO: TO TEST
[[plugins]]
repository = "OrangeT/vim-csharp"

