
" set guifont=DejaVu_Sans_Mono_for_Powerline
set guifont=Consolas
" Gui options
" default windows: egmrLtT
" default unix aegimrLtT
" e -> use GUI tabs (instead of console-like tabs
" R/L r/l -> Right/Left scrollbars always/when splitted
" B -> bottom scrollbar
set guioptions=

" GUI Cursor http://vimdoc.sourceforge.net/htmldoc/options.html#%27guicursor%27
"set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-Cursor/lCursor-blinkon0,r-cr:hor20-Cursor/lCursor,sm:block-Cursor-blinkwait175-blinkoff150-blinkon175

" Airline: enable powerline fonts
